# build
FROM golang:1.12 as build
ENV GO111MODULE=on

WORKDIR /go/src/github.com/k-yomo/go_echo_boilerplate

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN make build

# exec
FROM scratch
COPY --from=build /go/src/github.com/k-yomo/go_echo_boilerplate/bin/server ./server
EXPOSE 1323
ENTRYPOINT ["./server"]