version: '3.6'

services:
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: go_echo_api_boilerplate_development
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: realize start --server
    volumes:
      - .:/go/src/github.com/k-yomo/go_echo_api_boilerplate
    depends_on:
      - db
    ports:
      - 1323:1323
      - 5002:5002
    env_file:
      - .env
    environment:
      GOPATH: /go
      DB_HOST: db
      PORT: 1323

volumes:
  db_data:

