# build
FROM golang:1.12 as build
ENV GO111MODULE=on

WORKDIR /go/src/github.com/k-yomo/go_echo_api_boilerplate

COPY go.mod .
COPY go.sum .
RUN go mod download && go get github.com/oxequa/realize

COPY . .

ENTRY_POINT ["realize", "start", "--server"]
