// Package {{ .Package }} contains the types for schema '{{ schema .Schema }}'.
package {{ .Package }}

// GENERATED BY XO. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"encoding/csv"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/go-sql-driver/mysql"
)

