CREATE TABLE sms_reconfirmations (
  id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  user_id INT unsigned NOT NULL UNIQUE COMMENT 'ユーザーID',
  phone_number VARCHAR(20) NOT NULL UNIQUE COMMENT '電話番号',
  auth_code VARCHAR(255) NOT NULL COMMENT '認証コード',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'SMS再認証';
